# Site settings
title: My Website
email: 
description: "Repository of projects in engineering & ML, Sean Nachtrab"
baseurl: ""
url: "http://nachtraven.github.io"
github_username:  nachtraven

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
