# Site settings
title: Grounded - my Blog
email: 
description: "Thoughts and projects about ML & engineering, Sean Nachtrab"
baseurl: ""
url: "http://nachtraven.github.io"
github_username:  nachtraven

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
